package openapitool

import (
	"context"

	"github.com/basewarphq/bw/cmd/internal/cmdexec"
	"github.com/basewarphq/bw/cmd/internal/tool"
)

type Tool struct{}

func New() *Tool { return &Tool{} }

func (t *Tool) Name() string { return "openapi" }

func (t *Tool) RunsAfter() []string { return []string{"buf"} }

func (t *Tool) RequiredBinaries() []tool.BinaryRequirement {
	return []tool.BinaryRequirement{
		{Name: "openapi-down-convert", Reason: "convert OpenAPI 3.1 to 3.0 for client compatibility"},
	}
}

func (t *Tool) RequiredFiles() []tool.FileRequirement {
	return []tool.FileRequirement{
		{Path: "proto/openapi.json", Reason: "OpenAPI 3.1 specification generated by buf"},
	}
}

func (t *Tool) Gen(ctx context.Context, dir string) error {
	if err := tool.CheckFiles(dir, t.RequiredFiles()); err != nil {
		return err
	}
	return cmdexec.Run(
		ctx, dir, "openapi-down-convert",
		"--input", "proto/openapi.json",
		"--output", "proto/openapi-3.0.json",
	)
}
